### PR TITLE
#10 remove bumble dependency

### LINKED ISSUE #10: Not existed dependency
### Describe the bug

Firstly, thank you for offering many useful libraries!
I'm using clipboard which has dependency of the notify.
It seems some of this library's dependencies does not exist in npm registry anymore.

### How do we reproduce?

1. remove node_module
2. run `npm install`

### Expected behavior

install finished successfully

### Actual behavior

The error is thrown
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@bumble%2frxjs-log - Not found
npm ERR! 404 
npm ERR! 404  '@bumble/rxjs-log@^0.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@extend-chrome/notify'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Please complete the following information:

- Library Version: latest
- Operating System: Mac
- Browser: Chrome
- Node Version: 12.16.3

### PR DESCRIPTION
**Pull request by renamoo**
Community guidelines:

- [x] I have read and understand the
      [contributing guidelines](https://github.com/extend-chrome/.github/blob/master/CONTRIBUTING.md)
      and
      [code of conduct](https://github.com/extend-chrome/.github/blob/master/CODE_OF_CONDUCT.md)

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Not sure how I can write test for it

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers: #10 

### Description
Fix #10 
I assume `@bumble/chrome-rxjs` is migrated to `@extend-chrome/events-rxjs`.
Also removed `@bumble/rxjs-log` which does not look like used anymore

### CODE REVIEW

**Comment by renamoo** [comment]
BTW, I found links in PR template are not valid. Filed an [Issue](https://github.com/extend-chrome/.github/issues/2)

**Comment by jacksteamdev** [comment]
@renamoo LGTM! Thanks!

**Comment by renamoo** [comment]
@jacksteamdev Thank you for checking and merging! Could you release a new version on npm so that `npm install` will not fail?

**Comment by jacksteamdev** [comment]
I did it just now, thanks for reminding me! 😊

**Pull request merged**
